//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmLoginLog
    {
        public int LoginLogId { get; set; }
        public string Account { get; set; }
        public string Pwd { get; set; }
        public string LoginIp { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Result { get; set; }
    }
}
