//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeDBEntities : DbContext
    {
        public EmployeeDBEntities()
            : base("name=EmployeeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmDepartment> EmDepartment { get; set; }
        public virtual DbSet<EmException> EmException { get; set; }
        public virtual DbSet<EmLoginLog> EmLoginLog { get; set; }
        public virtual DbSet<EmPower> EmPower { get; set; }
        public virtual DbSet<EmRole> EmRole { get; set; }
        public virtual DbSet<EmUser> EmUser { get; set; }
    }
}
