//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmUser
    {
        public int UserId { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string UserAccount { get; set; }
        public string UserPwd { get; set; }
        public string UserRealName { get; set; }
        public string UserSex { get; set; }
        public string UserPhone { get; set; }
        public string UserPowerList { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
    }
}
